/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppFindingsRouteImport } from './routes/_app/findings'
import { Route as AppJiraRouteImport } from './routes/_app/jira'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as JoinInviteIdRouteImport } from './routes/join.$inviteId'
import { Route as AppContractsIndexRouteImport } from './routes/_app/contracts/index'
import { Route as AppContractsContractIdRouteImport } from './routes/_app/contracts/$contractId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsAiRouteImport } from './routes/_app/settings/ai'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings/audit'
import { Route as AppSettingsJiraRouteImport } from './routes/_app/settings/jira'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings/members'
import { Route as AppSettingsWatcherRouteImport } from './routes/_app/settings/watcher'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFindingsRoute = AppFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => AppRoute,
} as any)
const AppJiraRoute = AppJiraRouteImport.update({
  id: '/jira',
  path: '/jira',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const JoinInviteIdRoute = JoinInviteIdRouteImport.update({
  id: '/join/$inviteId',
  path: '/join/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContractsIndexRoute = AppContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsContractIdRoute = AppContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsJiraRoute = AppSettingsJiraRouteImport.update({
  id: '/jira',
  path: '/jira',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsWatcherRoute = AppSettingsWatcherRouteImport.update({
  id: '/watcher',
  path: '/watcher',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/findings': typeof AppFindingsRoute
  '/jira': typeof AppJiraRoute
  '/join/$inviteId': typeof JoinInviteIdRoute
  '/contracts/$contractId': typeof AppContractsContractIdRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/jira': typeof AppSettingsJiraRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/watcher': typeof AppSettingsWatcherRoute
  '/contracts/': typeof AppContractsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/findings': typeof AppFindingsRoute
  '/jira': typeof AppJiraRoute
  '/join/$inviteId': typeof JoinInviteIdRoute
  '/': typeof AppIndexRoute
  '/contracts/$contractId': typeof AppContractsContractIdRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/jira': typeof AppSettingsJiraRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/watcher': typeof AppSettingsWatcherRoute
  '/contracts': typeof AppContractsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_app/findings': typeof AppFindingsRoute
  '/_app/jira': typeof AppJiraRoute
  '/join/$inviteId': typeof JoinInviteIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/contracts/$contractId': typeof AppContractsContractIdRoute
  '/_app/settings/ai': typeof AppSettingsAiRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/jira': typeof AppSettingsJiraRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/watcher': typeof AppSettingsWatcherRoute
  '/_app/contracts/': typeof AppContractsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/findings'
    | '/jira'
    | '/join/$inviteId'
    | '/contracts/$contractId'
    | '/settings/ai'
    | '/settings/audit'
    | '/settings/jira'
    | '/settings/members'
    | '/settings/watcher'
    | '/contracts/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/findings'
    | '/jira'
    | '/join/$inviteId'
    | '/'
    | '/contracts/$contractId'
    | '/settings/ai'
    | '/settings/audit'
    | '/settings/jira'
    | '/settings/members'
    | '/settings/watcher'
    | '/contracts'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/settings'
    | '/_app/findings'
    | '/_app/jira'
    | '/join/$inviteId'
    | '/_app/'
    | '/_app/contracts/$contractId'
    | '/_app/settings/ai'
    | '/_app/settings/audit'
    | '/_app/settings/jira'
    | '/_app/settings/members'
    | '/_app/settings/watcher'
    | '/_app/contracts/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  JoinInviteIdRoute: typeof JoinInviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/findings': {
      id: '/_app/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof AppFindingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jira': {
      id: '/_app/jira'
      path: '/jira'
      fullPath: '/jira'
      preLoaderRoute: typeof AppJiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/join/$inviteId': {
      id: '/join/$inviteId'
      path: '/join/$inviteId'
      fullPath: '/join/$inviteId'
      preLoaderRoute: typeof JoinInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contracts/': {
      id: '/_app/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AppContractsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$contractId': {
      id: '/_app/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof AppContractsContractIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/jira': {
      id: '/_app/settings/jira'
      path: '/jira'
      fullPath: '/settings/jira'
      preLoaderRoute: typeof AppSettingsJiraRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/watcher': {
      id: '/_app/settings/watcher'
      path: '/watcher'
      fullPath: '/settings/watcher'
      preLoaderRoute: typeof AppSettingsWatcherRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsJiraRoute: typeof AppSettingsJiraRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsWatcherRoute: typeof AppSettingsWatcherRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsJiraRoute: AppSettingsJiraRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsWatcherRoute: AppSettingsWatcherRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppFindingsRoute: typeof AppFindingsRoute
  AppJiraRoute: typeof AppJiraRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContractsContractIdRoute: typeof AppContractsContractIdRoute
  AppContractsIndexRoute: typeof AppContractsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppFindingsRoute: AppFindingsRoute,
  AppJiraRoute: AppJiraRoute,
  AppIndexRoute: AppIndexRoute,
  AppContractsContractIdRoute: AppContractsContractIdRoute,
  AppContractsIndexRoute: AppContractsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  JoinInviteIdRoute: JoinInviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
