#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# This one sets up the live Jira test (e2e/live/jira-smoke.ts): it gets AuditIQ connected
# to a real Jira Cloud sandbox, gets a reviewer account signed in, and runs the test.
# Run it from anywhere: e2e/live/setup.sh
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from the repository root, so `pnpm smoke:jira` and the paths below resolve.
cd "$(dirname "$0")/../.."

# Answers that aren't secret are saved here between runs. Tokens are never saved: AuditIQ's
# goes straight into its settings page, and the reviewer's lives only in this process.
ENV_FILE="e2e/.artifacts/live/smoke.env"
mkdir -p "$(dirname "$ENV_FILE")"
COOKIES=$(mktemp)
trap 'rm -f "$COOKIES"' EXIT
TOTAL_STAGES=5

# ask_saved KEY "Prompt" — ask, showing the value saved from an earlier run.
ask_saved() {
  local current
  current=$(_existing "$1" || true)
  [[ -n "$current" ]] && note "Saved: $current"
  ask "$1" "$2"
}

# auditiq METHOD PATH [JSON] — call AuditIQ's API as the signed-in admin.
auditiq() {
  if [[ -n "${3:-}" ]]; then
    printf '%s' "$3" | curl -sS -m 300 -X "$1" -b "$COOKIES" -c "$COOKIES" -H "Origin: $AUDITIQ_API" \
      -H "Content-Type: application/json" --data-binary @- "$AUDITIQ_API$2"
  else
    curl -sS -m 30 -X "$1" -b "$COOKIES" -c "$COOKIES" -H "Origin: $AUDITIQ_API" "$AUDITIQ_API$2"
  fi
}

# json 'expression' — evaluate a JavaScript expression against JSON on stdin (as `d`).
json() {
  node -e 'let d = {}; try { d = JSON.parse(require("fs").readFileSync(0, "utf8")); } catch {} const v = eval(process.argv[1]); console.log(v ?? "")' "$1"
}

# jira_myself URL — GET /myself as the reviewer. The token goes in on stdin, never in argv.
jira_myself() {
  printf 'user = "%s:%s"\n' "$JIRA_REVIEWER_EMAIL" "$JIRA_REVIEWER_TOKEN" |
    curl -sS -m 20 -K - -w '\n%{http_code}' "$1/rest/api/3/myself" 2>/dev/null || printf '\n000'
}

banner "AuditIQ live Jira test"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Check AuditIQ is running"
say "The test drives your AuditIQ server and publishes findings from a contract"
say "it has already analyzed."
printf '\n'
ask_saved AUDITIQ_API "AuditIQ's API address (the dev server is http://127.0.0.1:5180):"
ask_saved AUDITIQ_WEB "The address you open AuditIQ at in the browser:"
ask_saved AUDITIQ_EMAIL "An AuditIQ admin's email:"
AUDITIQ_PASSWORD="${AUDITIQ_PASSWORD:-}"
if [[ -z "$AUDITIQ_PASSWORD" ]]; then
  ask_secret AUDITIQ_PASSWORD "Their password (Enter for the dev account's):"
  AUDITIQ_PASSWORD="${AUDITIQ_PASSWORD:-correct-horse-battery}"
fi
write_env AUDITIQ_API "$AUDITIQ_API"
write_env AUDITIQ_WEB "$AUDITIQ_WEB"
write_env AUDITIQ_EMAIL "$AUDITIQ_EMAIL"

until curl -sS -m 5 "$AUDITIQ_API/api/setup/state" >/dev/null 2>&1; do
  warn "AuditIQ isn't answering at $AUDITIQ_API. Start it with: pnpm dev"
  pause "Press Enter to check again."
done
signin=$(printf '{"email":"%s","password":"%s"}' "$AUDITIQ_EMAIL" "$AUDITIQ_PASSWORD" |
  curl -sS -m 15 -o /dev/null -w '%{http_code}' -c "$COOKIES" -H "Origin: $AUDITIQ_API" \
    -H "Content-Type: application/json" --data-binary @- "$AUDITIQ_API/api/auth/sign-in/email")
if [[ "$signin" != "200" ]]; then
  warn "AuditIQ rejected that email and password ($signin). Re-run the wizard to try again."
  exit 1
fi
until [[ "$(auditiq GET /api/contracts | json 'd.contracts.filter(c => c.findings.high + c.findings.medium + c.findings.low > 0).length')" -gt 0 ]]; do
  warn "AuditIQ has no contract with findings yet. Upload one at $AUDITIQ_WEB and wait for Extraction."
  pause "Press Enter to check again."
done
say "${GREEN}✓${RESET} AuditIQ is running, you're signed in, and there's a contract with findings."
pause "Press Enter to continue."

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Pick the Jira account AuditIQ acts as"
say "AuditIQ creates issues and posts replies as one Atlassian account. The test also"
say "needs someone to play the person working in Jira: you."
printf '\n'
say "AuditIQ ignores comments from its own account, so testing @AuditIQ replies"
say "needs two accounts. Gmail ignores anything after a +, so you+auditiq@gmail.com"
say "lands in your normal inbox but counts as a separate Atlassian account."
printf '\n'
if confirm "Give AuditIQ its own account? (Without one, the test skips @mention replies.)"; then
  SEPARATE_ACCOUNT=yes
  open_url "https://admin.atlassian.com"
  step "Pick your organization if asked, then Directory → Users → Invite users."
  note "  On the older admin layout: Invite → Users."
  step "Enter the new address, for example you+auditiq@gmail.com."
  step "Give it a Jira user role and untick any other apps, then select Invite users."
  step "Open the invite email, finish signing up, and name the account AuditIQ."
  step "If your sandbox project only lets certain people in, add the account there too."
  printf '\n'
  ask_saved JIRA_SERVICE_EMAIL "The AuditIQ account's email:"
else
  SEPARATE_ACCOUNT=no
  say "AuditIQ will act as you. Everything except the @mention replies gets tested."
  ask_saved JIRA_SERVICE_EMAIL "Your Atlassian email:"
fi
write_env JIRA_SERVICE_EMAIL "$JIRA_SERVICE_EMAIL"
write_env SEPARATE_ACCOUNT "$SEPARATE_ACCOUNT"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Connect AuditIQ to Jira"
ask_saved JIRA_SITE "Your Jira site (https://your-site.atlassian.net):"
JIRA_SITE="${JIRA_SITE%/}"
write_env JIRA_SITE "$JIRA_SITE"
printf '\n'
if [[ "$SEPARATE_ACCOUNT" == "yes" ]]; then
  say "Create the token while signed in as the AuditIQ account. Use a private window so"
  say "your own session stays put, and open this address in it:"
  say "${BOLD}https://id.atlassian.com/manage-profile/security/api-tokens${RESET}"
else
  open_url "https://id.atlassian.com/manage-profile/security/api-tokens"
fi
step "Sign in as $JIRA_SERVICE_EMAIL. Atlassian may email a one-time code first."
step "Select Create API token (the plain one, not \"with scopes\") and name it AuditIQ."
step "Keep the default one-year expiry, select Create, then Copy to clipboard."
printf '\n'
say "Paste the token into AuditIQ, not here. This wizard never sees it."
open_url "$AUDITIQ_WEB/settings/jira"
step "Site URL: $JIRA_SITE"
step "Email: $JIRA_SERVICE_EMAIL. API token: paste it. Then select Connect."
step "Under \"Where findings go\", pick your sandbox project and the Task issue type."
step "Check the priority mapping, then select Save."
printf '\n'
pause "Press Enter once AuditIQ says Connected and the project is saved."
while :; do
  settings=$(auditiq GET /api/settings/jira)
  problem=$(printf '%s' "$settings" | json "
    !d.displayName || d.tokenReadable === false ? 'AuditIQ has no working Jira connection yet.'
    : d.email.toLowerCase() !== '${JIRA_SERVICE_EMAIL,,}' ? 'AuditIQ is connected as ' + d.email + ', not $JIRA_SERVICE_EMAIL.'
    : !d.projectKey || !d.issueTypeId ? 'Pick a project and issue type, then Save.'
    : ''")
  [[ -z "$problem" ]] && break
  warn "$problem"
  pause "Fix it in AuditIQ, then press Enter to check again."
done
JIRA_SITE=$(printf '%s' "$settings" | json 'd.siteUrl')
PROJECT=$(printf '%s' "$settings" | json 'd.projectKey')
SERVICE_ID=$(printf '%s' "$settings" | json 'd.accountId')
say "${GREEN}✓${RESET} AuditIQ acts as $(printf '%s' "$settings" | json 'd.displayName') and publishes to $PROJECT."
pause "Press Enter to continue."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Sign the reviewer in"
say "The reviewer is you. The test signs in as you to check what AuditIQ wrote,"
say "move one issue along, and ask AuditIQ a question in a comment."
printf '\n'
if [[ "$SEPARATE_ACCOUNT" == "yes" ]]; then
  open_url "https://id.atlassian.com/manage-profile/security/api-tokens"
  step "In your normal window, signed in as yourself, select Create API token."
  step "Name it \"AuditIQ smoke test\", pick an expiry a week or so out, Create, then Copy."
  printf '\n'
  ask_saved JIRA_REVIEWER_EMAIL "Your Atlassian email:"
else
  JIRA_REVIEWER_EMAIL="$JIRA_SERVICE_EMAIL"
  say "Same account as AuditIQ. Paste the token you just made, or create another at"
  say "https://id.atlassian.com/manage-profile/security/api-tokens"
fi
while :; do
  ask_secret JIRA_REVIEWER_TOKEN "Paste the token (hidden, never saved):"
  reply=$(jira_myself "$JIRA_SITE")
  if [[ "${reply##*$'\n'}" != "200" ]]; then
    # Scoped tokens only work through api.atlassian.com.
    cloud=$(curl -sS -m 10 "$JIRA_SITE/_edge/tenant_info" 2>/dev/null | json 'd.cloudId')
    [[ -n "$cloud" ]] && reply=$(jira_myself "https://api.atlassian.com/ex/jira/$cloud")
  fi
  [[ "${reply##*$'\n'}" == "200" ]] && break
  warn "Jira didn't accept $JIRA_REVIEWER_EMAIL with that token (${reply##*$'\n'}). Try again."
done
write_env JIRA_REVIEWER_EMAIL "$JIRA_REVIEWER_EMAIL"
reviewer_id=$(printf '%s' "${reply%$'\n'*}" | json 'd.accountId')
say "${GREEN}✓${RESET} Signed in to Jira as $(printf '%s' "${reply%$'\n'*}" | json 'd.displayName')."
if [[ "$SEPARATE_ACCOUNT" == "yes" && "$reviewer_id" == "$SERVICE_ID" ]]; then
  warn "That's the same account AuditIQ uses, so the test will skip the @mention steps."
fi
pause "Press Enter to continue."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Run the live test"
say "The test writes to $PROJECT on $JIRA_SITE:"
step "publishes up to 3 findings (or links them, if an earlier run already did)"
step "checks each issue through Jira's API, then publishes again to prove nothing duplicates"
step "moves one issue to another status, assigns it to you, and checks AuditIQ sees it"
step "with two accounts, asks AuditIQ two questions: one in shadow mode, one in assist"
note "  The questions make a few small calls to AuditIQ's AI provider."
note "  Everything stays in $PROJECT afterwards for you to look at."
printf '\n'
SMOKE_EXIT=""
if confirm "Run it now?"; then
  printf '\n'
  set +e
  JIRA_REVIEWER_EMAIL="$JIRA_REVIEWER_EMAIL" JIRA_REVIEWER_TOKEN="$JIRA_REVIEWER_TOKEN" \
    AUDITIQ_URL="$AUDITIQ_API" AUDITIQ_EMAIL="$AUDITIQ_EMAIL" AUDITIQ_PASSWORD="$AUDITIQ_PASSWORD" \
    pnpm --silent smoke:jira
  SMOKE_EXIT=$?
  set -e
  printf '\n'
  pause "Press Enter for the summary."
else
  SKIPPED+=("Run the test: JIRA_REVIEWER_EMAIL=$JIRA_REVIEWER_EMAIL JIRA_REVIEWER_TOKEN=<token> pnpm smoke:jira")
fi
# ──────────────────────────────────────────────────────────────────────────

finish
if [[ -n "$SMOKE_EXIT" ]]; then
  report=$(ls -t e2e/.artifacts/live/*/report.md 2>/dev/null | head -n1 || true)
  if [[ "$SMOKE_EXIT" == "0" ]]; then say "${GREEN}✓ The live Jira test passed.${RESET}"; else warn "The live Jira test failed."; fi
  [[ -n "$report" ]] && note "Report: $report"
  printf '\n'
fi
